### ISSUE TITLE
quadraticCurveTo

### ISSUE THREAD

**Issue by ruchirlives** [emilefokkema/infinite-canvas-2#13]
quadraticCurveTo is seemingly not working in this implementation.

**Comment by emilefokkema** [comment]
You're absolutely right. I must have forgotten to implement it. I'll see when I get around to it. (Same goes for `bezierCurveTo` by the way.)

**Comment by ruchirlives** [comment]
No probs. Hopefully quite straightforward. BTW, is there a way to set the zoom and pan state of the canvas, a method?

**Comment by emilefokkema** [comment]
Nope! Another missing feature ;)

**Comment by emilefokkema** [comment]
@ruchirlives I added support for `quadraticCurveTo` in the newest release ([0.5.1-alpha](https://github.com/emilefokkema/infinite-canvas/releases/tag/v0.5.1-alpha), released just now).

**Comment by emilefokkema** [comment]
added support for `bezierCurveTo` as well, in [v0.5.3-alpha](https://github.com/emilefokkema/infinite-canvas/releases/tag/v0.5.3-alpha).
